# Generated by Django 3.0.6 on 2020-06-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneunit',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='oneunit',
            name='description',
            field=models.TextField(max_length=360, null=True),
        ),
    ]
