# Generated by Django 3.0.6 on 2020-06-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200602_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneunit',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
