# Generated by Django 3.0.6 on 2020-06-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200602_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneunit',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
