# Generated by Django 3.0.6 on 2020-06-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200604_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneunit',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
