# Generated by Django 3.0.6 on 2020-06-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200604_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneunit',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
