# Generated by Django 3.0.6 on 2020-06-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200604_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneunit',
            name='image',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
