# Generated by Django 3.0.6 on 2020-06-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200604_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneunit',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
